FROM tomcat:8-jre11
LABEL “Project”=”Docker-Demo”
LABEL “Author”=”Neeraj”
RUN rm -rf /usr/local/tomcat/webapp/*
COPY target/Demo-app.war /usr/local/tomcat/webapp/ROOT.war
EXPOSE 8080
CMD [“ atalina.sh”, “run”]
WORKDIR /usr/local/tomcat/
VOLUME /usr/local/tomcat/webapp
