apiVersion: apps/v1
kind: Deployment
metadata:
  name: My_Spring_Boot_Application
spec:
  selector:
    matchLabels:
      app: My_Spring_Boot_Application
  strategy:
    type: RollingUpdate 
    rollingUpdate:
      maxUnavailable: 1 
      maxSurge: 3 
  replicas: 4 
  revisionHistoryLimit: 15
  template:
    metadata:
      labels:
        app: My_Spring_Boot_Application
    spec:
      containers:
      - image: repo/demo:0.0.1-SNAPSHOT
        name: My_Spring_Boot_Application
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
