pipeline {
    agent any

    stages {
        stage('Checkout') {  
            steps {
                git branch: 'main', url: 'https://github.com/your/repository.git'
            }
        }
        
        stage('Build') {  
            steps {
                sh 'mvn clean package'
            }
        }

        stage('Test') {  
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/Test-reports/**/*.xml'
                }
            }
        }

        stage('Publish Artifact') {  
            steps {
                sh 'mvn deploy'
            }
        }
    }
}
